var allProducts = [
    new Product('1', '4K Smart Monitor Vantablack Expo GPS-8377366J',
        '$1,150', '', 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '11', 'Computer', 'Computers, Equipment',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-11.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-11-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-11-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-11-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-11-3.jpg'],
        '--isnew:true'),

    new Product('2', 'SX-2357 Closed-Back Wireless Headphones',
        '$630', '', 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '06', 'Audio', 'USB, Wireless',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-10.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-10-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-10-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-10-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-10-4.jpg'],
        ''),

    new Product('3', 'BX-2357 Closed-Back Wireless Headphones',
        '$700', '', 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '09', 'Audio', 'USB, Wireless',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-9.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-9-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-9-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-9-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-9-3.jpg'],
        ''),


    new Product('4', 'Fixed-Wing Hybrid VTOL Surveillance Drone',
        `$1,100`, `$1,450`, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '08', 'Digital Tech', 'USB, Wireless',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-8.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-8-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-8-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-8-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-8-3.jpg'],
        ''),

    new Product('5', 'Business Inkjet All In One Printer 752-DLLW-888',
        `$750`, ``, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '07', 'Printers', 'Computers, Equipment',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-7.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-7-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-7-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-7-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-7-3.jpg'],
        ''),

    new Product('6', 'Led 4K Smart TV Vantablack Expo GSM-8547366J',
        `$990`, ``, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '06', 'Computers', 'USB, Wireless',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6-2.jpg'],
        ''),

    new Product('7', 'Electric Scooter B&W TP58921XM Prisma XX Series',
        `$450`, ``, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '02', 'Electronics', 'USB, Wireless',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-2-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-2-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-2-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-2-4.jpg'],
        ''),

    new Product('8', 'Optical Mouse Pro XS-85477PGT Carbon Black',
        `$120`, `$170`, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '01', 'Other', 'Computers, Equipment',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-1-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-1-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-1-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-1-3.jpg'],
        ''),

    new Product('9', 'Robot Vacuum Cleaner Samba W',
        '$890', '', 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '12', 'Robotic', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-12.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-12-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-12-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-12-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-12-3.jpg'],
        '--isnew:true'),

    new Product('10', 'Air Purifier Mika Clean Pro-559',
        '$1,390', '', 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '13', 'Other', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-13.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-13-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-13-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-13-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-13-4.jpg'],
        ''),

    new Product('11', 'Universal Black Smartphone Case',
        '$80', '', 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '15', 'Smartphones', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-14.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-14-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-14-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-14-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-14-3.jpg'],
        ''),


    new Product('12', 'Bluetooth Speaker GS-99 Silver',
        `$290`, `$1,450`, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '16', 'Bluetooth', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-15.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-15-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-15-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-15-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-15-3.jpg'],
        ''),

    new Product('13', 'Profeus Drawing Tablet S Series QW-55815 Professional',
        `$930`, `$1,090`, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '14', 'Tablet', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-4-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-4-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-4-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-4-2.jpg'],
        ''),

    new Product('14', 'High Definition Webcam SX-555',
        `$140`, ``, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '19', 'Camera', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-18.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-18-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-18-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-18-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-18-3.jpg'],
        ''),

    new Product('15', 'Waterproof Smart Watch Black',
        `$230`, ``, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '18', 'Watch', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-17.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-17-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-17-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-17-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-17-3.jpg'],
        ''),

    new Product('16', 'Led 4K Smart TV Expo GSX White',
        `$1,590`, ``, 'Lorem ipsum odor amet, consectetuer adipiscing elit. Ac varius cubilia pretium eleifend cubilia fringilla. Pharetra nec blandit magnis dolor mauris feugiat. Pretium odio fringilla cubilia turpis eros ridiculus mauris.',
        '20', 'Computer', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-19.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-6-4.jpg'],
        ''),

    new Product('17', '2TB SSD 3D TLC 6Gb/s 2.5″ Internal Solid State Drive T253A300',
        `$450`, ``, 'Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expete mei. Mei an consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id, error epicurei mea et. Qui purto zril laoreet. Ex error omnium interpretaris pro.',
        '292', 'External SSDs', 'USB, Wireless',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-110.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-110-4.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-110-2.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-110-3.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-110-1.png'],
        ''),

    new Product('18', '2TB USB 3.1 External Hard Drive Orange',
        `$210`, ``, 'Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expete mei. Mei an consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id, error epicurei mea et. Qui purto zril laoreet. Ex error omnium interpretaris pro.',
        '299', 'USB Flesh', 'USB, Wireless',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-117.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-117-3.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-117-4.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-117-1.png', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-117-2.png'],
        ''),

    new Product('19', 'Over-Ear FX-525 Light Headphones',
        `$890`, ``, 'Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expete mei. Mei an consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id, error epicurei mea et. Qui purto zril laoreet. Ex error omnium interpretaris pro.',
        '341', 'Audio', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-76-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-29-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-29-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-29-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-29-3.jpg'],
        ''),

    new Product('20', 'Camera CCQ-55889 4k Waterproof Cover',
        `$1,050`, ``, 'Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expete mei. Mei an consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id, error epicurei mea et. Qui purto zril laoreet. Ex error omnium interpretaris pro.',
        '339', 'Camera', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-40.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-40-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-40-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-40-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-40-3.jpg'],
        ''),

    new Product('21', 'Profeus Laptop 64GB W Series QW-55814',
        `$870`, ``, '4.5 inch HD Touch Screen (1280 x 720), Android 4.4 Lorem OS, 1.4 GHz Ipsum Amet Processor, 20 MP front and 28 megapixel CMOX camera',
        '338', 'Laptop', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-30.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-3-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-3-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-3-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/08/shop-img-3-4.jpg'],
        '--isnew:true'),

    new Product('22', 'Smart Watch Fitness Tracker GS-87 Black',
        `$450`, ``, 'Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expete mei. Mei an consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id, error epicurei mea et. Qui purto zril laoreet. Ex error omnium interpretaris pro.',
        '337', 'Watch', 'Tech',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-28.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-28-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-28-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-28-3.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-28-4.jpg'],
        ''),

    new Product('23', 'USB Cable P-5001 Printer/Laptop/Phone',
        `$45`, ``, 'Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expete mei. Mei an consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id, error epicurei mea et. Qui purto zril laoreet. Ex error omnium interpretaris pro.',
        '333', 'Cables and Adapters', '',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-49.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-49.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-49.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-49.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-49.jpg'],
        ''),

    new Product('23', 'High-Airflow CXC-77 Computer Case Blue',
        `$3,850`, ``, 'Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expete mei. Mei an consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id, error epicurei mea et. Qui purto zril laoreet. Ex error omnium interpretaris pro.',
        '331', 'Block', 'Memory, Storage',
        ['https://gizmos.qodeinteractive.com/wp-content/uploads/2022/10/shop-img-122.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-75-4.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-75-1.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-75-2.jpg', 'https://gizmos.qodeinteractive.com/wp-content/uploads/2022/09/shop-img-75-3.jpg'],
        ''),
]